---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define standard packages
  set_fact:
      standard_packages: "{{ __standard_packages | list }}"
  when: standard_packages is not defined

- name: include os-specific setup
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: include os-specific configuration
  include_tasks: "configure-{{ ansible_os_family }}.yml"
