set t_Co=256
filetype plugin indent on
set cursorline
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
syntax enable
set number
set undofile
set undodir=~/.vimundo/
set backspace=indent,eol,start
colors azuki
