set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'file:///home/gmarik/path/to/plugin'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'sheerun/vim-polyglot'
call vundle#end()
filetype plugin indent on

set t_Co=256
set cursorline
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
syntax enable
set number
set undofile
set undodir=~/.vimundo/
set backspace=indent,eol,start
colors azuki
